### ISSUE TITLE
Moderation stream selector not registering change

### ISSUE THREAD

**Issue by thomasgwatson** [Hylozoic/hylo#82]
Direct URL for `/proposals?d=moderation` works but it doesn't work via click navigation.

https://staging.hylo.com/groups/building-hylo/proposals?d=moderation

Likely that a change in the url is not being registered as a need for an update.

![Screenshot 2024-11-21 at 11 28 57 AM](https://github.com/user-attachments/assets/a9f17743-6cb3-4cb4-839c-247b03c1874f)

**Comment by tibetsprague** [comment]
fixed!
