### ISSUE TITLE
Several "My Home" queries don't seem to work on front-end?

### ISSUE THREAD

**Issue by thomasgwatson** [Hylozoic/hylo#90]
I don't think posts, interactions or mentions work

![Screenshot 2024-11-30 at 11 10 42 AM](https://github.com/user-attachments/assets/e71a1a86-a14c-4740-802a-fddc474b9ceb)

**Comment by tibetsprague** [comment]
weird, they work for me locally

**Comment by tibetsprague** [comment]
actually they work for me on staging too!

**Comment by KrishaTerranIO** [comment]
This is working for me as well
